# Source Generated with Decompyle++
# File: extract/AC_SIM.exe_extracted/PYZ-00.pyz_extracted/Ui_mainWindow.pyc (Python 3.9)

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName('MainWindow')
        MainWindow.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 480))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 480))
        self.centralwidget.setMaximumSize(QtCore.QSize(1024, 768))
        self.centralwidget.setStyleSheet('QWidget {\nbackground-color: qlineargradient(spread:pad, x1:1, y1:0.851, x2:1, y2:0, stop:0 rgba(0, 5, 11, 255), stop:1 rgba(18, 90, 165, 255));\n}')
        self.centralwidget.setObjectName('centralwidget')
        self.labelVersione = QtWidgets.QLabel(self.centralwidget)
        self.labelVersione.setGeometry(QtCore.QRect(20, 435, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelVersione.setFont(font)
        self.labelVersione.setStyleSheet('background:transparent;\ncolor:white')
        self.labelVersione.setObjectName('labelVersione')
        self.frameMain = QtWidgets.QFrame(self.centralwidget)
        self.frameMain.setGeometry(QtCore.QRect(170, 0, 631, 481))
        self.frameMain.setStyleSheet('background:transparent;')
        self.frameMain.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameMain.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameMain.setObjectName('frameMain')
        self.pushButtonImpostazioniAdmin = QtWidgets.QToolButton(self.frameMain)
        self.pushButtonImpostazioniAdmin.setGeometry(QtCore.QRect(4800, 170, 111, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonImpostazioniAdmin.setFont(font)
        self.pushButtonImpostazioniAdmin.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.pushButtonImpostazioniAdmin.setStyleSheet('QToolButton{\nbackground:#d3ded3;\ncolor:black;\n}\nQToolButton:!enabled{\nbackground:#d3ded3;\ncolor:white;\n}')
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap('pics/settings-50.png'), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonImpostazioniAdmin.setIcon(icon)
        self.pushButtonImpostazioniAdmin.setIconSize(QtCore.QSize(50, 50))
        self.pushButtonImpostazioniAdmin.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.pushButtonImpostazioniAdmin.setObjectName('pushButtonImpostazioniAdmin')
        self.pushButtonRiepilogo = QtWidgets.QToolButton(self.frameMain)
        self.pushButtonRiepilogo.setGeometry(QtCore.QRect(690, 100, 111, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonRiepilogo.setFont(font)
        self.pushButtonRiepilogo.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.pushButtonRiepilogo.setStyleSheet('QToolButton{\nbackground:#d3ded3;\ncolor:black;\n}\nQToolButton:!enabled{\nbackground:#d3ded3;\ncolor:white;\n}')
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap('pics/bar_chart-50_mod_tr.png'), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonRiepilogo.setIcon(icon1)
        self.pushButtonRiepilogo.setIconSize(QtCore.QSize(50, 50))
        self.pushButtonRiepilogo.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.pushButtonRiepilogo.setObjectName('pushButtonRiepilogo')
        self.labelWaiting = QtWidgets.QLabel(self.frameMain)
        self.labelWaiting.setGeometry(QtCore.QRect(70, 100, 401, 221))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelWaiting.setFont(font)
        self.labelWaiting.setStyleSheet('background:transparent;\ncolor:white;\nfont:40px;')
        self.labelWaiting.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelWaiting.setObjectName('labelWaiting')
        self.frameImpostazioni = QtWidgets.QFrame(self.centralwidget)
        self.frameImpostazioni.setGeometry(QtCore.QRect(1700, 0, 631, 481))
        self.frameImpostazioni.setStyleSheet('background:transparent;')
        self.frameImpostazioni.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameImpostazioni.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameImpostazioni.setObjectName('frameImpostazioni')
        self.pushButtonEsciImpostazioni = QtWidgets.QToolButton(self.frameImpostazioni)
        self.pushButtonEsciImpostazioni.setGeometry(QtCore.QRect(510, 360, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonEsciImpostazioni.setFont(font)
        self.pushButtonEsciImpostazioni.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.pushButtonEsciImpostazioni.setStyleSheet('QToolButton{\nbackground:#d3ded3;\ncolor:black;\n}\nQToolButton:!enabled{\nbackground:#d3ded3;\ncolor:white;\n}')
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap('pics/left2-50.png'), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonEsciImpostazioni.setIcon(icon2)
        self.pushButtonEsciImpostazioni.setIconSize(QtCore.QSize(35, 35))
        self.pushButtonEsciImpostazioni.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.pushButtonEsciImpostazioni.setObjectName('pushButtonEsciImpostazioni')
        self.labelLingua = QtWidgets.QLabel(self.frameImpostazioni)
        self.labelLingua.setGeometry(QtCore.QRect(160, 60, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelLingua.setFont(font)
        self.labelLingua.setStyleSheet('color:white;')
        self.labelLingua.setObjectName('labelLingua')
        self.comboBoxLingua = QtWidgets.QComboBox(self.frameImpostazioni)
        self.comboBoxLingua.setGeometry(QtCore.QRect(160, 100, 201, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBoxLingua.setFont(font)
        self.comboBoxLingua.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.comboBoxLingua.setStyleSheet('background:white;\ncolor:black;')
        self.comboBoxLingua.setObjectName('comboBoxLingua')
        self.labelValuta = QtWidgets.QLabel(self.frameImpostazioni)
        self.labelValuta.setGeometry(QtCore.QRect(1600, 230, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelValuta.setFont(font)
        self.labelValuta.setStyleSheet('color:white;')
        self.labelValuta.setObjectName('labelValuta')
        self.comboBoxValuta = QtWidgets.QComboBox(self.frameImpostazioni)
        self.comboBoxValuta.setGeometry(QtCore.QRect(1600, 270, 201, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBoxValuta.setFont(font)
        self.comboBoxValuta.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.comboBoxValuta.setStyleSheet('background:white;\ncolor:black;')
        self.comboBoxValuta.setObjectName('comboBoxValuta')
        self.labelJCM = QtWidgets.QLabel(self.frameImpostazioni)
        self.labelJCM.setGeometry(QtCore.QRect(160, 160, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelJCM.setFont(font)
        self.labelJCM.setStyleSheet('color:white;')
        self.labelJCM.setObjectName('labelJCM')
        self.comboBoxJCM = QtWidgets.QComboBox(self.frameImpostazioni)
        self.comboBoxJCM.setGeometry(QtCore.QRect(160, 210, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.comboBoxJCM.setFont(font)
        self.comboBoxJCM.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.comboBoxJCM.setStyleSheet('background:white;\ncolor:black;\nfont:22px;')
        self.comboBoxJCM.setObjectName('comboBoxJCM')
        self.comboBoxJCM.addItem('')
        self.comboBoxJCM.addItem('')
        self.pushButtonClean = QtWidgets.QToolButton(self.frameImpostazioni)
        self.pushButtonClean.setGeometry(QtCore.QRect(160, 290, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonClean.setFont(font)
        self.pushButtonClean.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.pushButtonClean.setStyleSheet('QToolButton{\nbackground:#d3ded3;\ncolor:black;\n}\nQToolButton:!enabled{\nbackground:#d3ded3;\ncolor:white;\n}')
        self.pushButtonClean.setIconSize(QtCore.QSize(35, 35))
        self.pushButtonClean.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.pushButtonClean.setObjectName('pushButtonClean')
        self.labelVNE = QtWidgets.QLabel(self.centralwidget)
        self.labelVNE.setGeometry(QtCore.QRect(20, 10, 101, 51))
        self.labelVNE.setStyleSheet('image: url(pics/logoVNE100.png);\nbackground:transparent;')
        self.labelVNE.setText('')
        self.labelVNE.setObjectName('labelVNE')
        self.frameVendita = QtWidgets.QFrame(self.centralwidget)
        self.frameVendita.setGeometry(QtCore.QRect(1200, 10, 661, 421))
        self.frameVendita.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.frameVendita.setStyleSheet('background:#d3d3d3;\ncolor:black;\nborder-style:solid;\nborder-width:1px;\nborder-color:black;\nborder-radius:10px;')
        self.frameVendita.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameVendita.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameVendita.setObjectName('frameVendita')
        self.frameVenditaInCorso = QtWidgets.QFrame(self.frameVendita)
        self.frameVenditaInCorso.setGeometry(QtCore.QRect(380, 10, 291, 371))
        self.frameVenditaInCorso.setStyleSheet('border:0px;')
        self.frameVenditaInCorso.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameVenditaInCorso.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameVenditaInCorso.setObjectName('frameVenditaInCorso')
        self.labelVenditaInCorso = QtWidgets.QLabel(self.frameVenditaInCorso)
        self.labelVenditaInCorso.setGeometry(QtCore.QRect(0, 0, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelVenditaInCorso.setFont(font)
        self.labelVenditaInCorso.setStyleSheet('color:black;\nbackground-color: transparent;\nborder:0px;')
        self.labelVenditaInCorso.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelVenditaInCorso.setObjectName('labelVenditaInCorso')
        self.labelVenditaRichiesto = QtWidgets.QLabel(self.frameVenditaInCorso)
        self.labelVenditaRichiesto.setGeometry(QtCore.QRect(10, 60, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelVenditaRichiesto.setFont(font)
        self.labelVenditaRichiesto.setStyleSheet('color:black;\nbackground-color: transparent;\nborder:0px;')
        self.labelVenditaRichiesto.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight | QtCore.Qt.AlignmentFlag.AlignTrailing | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelVenditaRichiesto.setObjectName('labelVenditaRichiesto')
        self.labelVenditaInserito = QtWidgets.QLabel(self.frameVenditaInCorso)
        self.labelVenditaInserito.setGeometry(QtCore.QRect(10, 110, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelVenditaInserito.setFont(font)
        self.labelVenditaInserito.setStyleSheet('color:black;\nbackground-color: transparent;\nborder:0px;')
        self.labelVenditaInserito.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight | QtCore.Qt.AlignmentFlag.AlignTrailing | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelVenditaInserito.setObjectName('labelVenditaInserito')
        self.labelVenditaResto = QtWidgets.QLabel(self.frameVenditaInCorso)
        self.labelVenditaResto.setGeometry(QtCore.QRect(30, 160, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelVenditaResto.setFont(font)
        self.labelVenditaResto.setStyleSheet('color:black;\nbackground-color: transparent;\nborder:0px;')
        self.labelVenditaResto.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight | QtCore.Qt.AlignmentFlag.AlignTrailing | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelVenditaResto.setObjectName('labelVenditaResto')
        self.lineEditRichiesto = QtWidgets.QLineEdit(self.frameVenditaInCorso)
        self.lineEditRichiesto.setGeometry(QtCore.QRect(150, 60, 111, 36))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEditRichiesto.setFont(font)
        self.lineEditRichiesto.setStyleSheet('border-style:solid;\nborder-width:1px;\nborder-color:black;\nborder-radius:10px;')
        self.lineEditRichiesto.setReadOnly(True)
        self.lineEditRichiesto.setObjectName('lineEditRichiesto')
        self.lineEditInserito = QtWidgets.QLineEdit(self.frameVenditaInCorso)
        self.lineEditInserito.setGeometry(QtCore.QRect(150, 110, 111, 36))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEditInserito.setFont(font)
        self.lineEditInserito.setStyleSheet('border-style:solid;\nborder-width:1px;\nborder-color:black;\nborder-radius:10px;')
        self.lineEditInserito.setReadOnly(True)
        self.lineEditInserito.setObjectName('lineEditInserito')
        self.lineEditResto = QtWidgets.QLineEdit(self.frameVenditaInCorso)
        self.lineEditResto.setGeometry(QtCore.QRect(150, 160, 111, 36))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEditResto.setFont(font)
        self.lineEditResto.setStyleSheet('border-style:solid;\nborder-width:1px;\nborder-color:black;\nborder-radius:10px;')
        self.lineEditResto.setReadOnly(True)
        self.lineEditResto.setObjectName('lineEditResto')
        self.labelVenditaMess = QtWidgets.QLabel(self.frameVenditaInCorso)
        self.labelVenditaMess.setGeometry(QtCore.QRect(50, 230, 211, 101))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelVenditaMess.setFont(font)
        self.labelVenditaMess.setStyleSheet('color:black;\nbackground-color: transparent;\nborder:0px;\nfont:16px;')
        self.labelVenditaMess.setText('')
        self.labelVenditaMess.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelVenditaMess.setObjectName('labelVenditaMess')
        self.labelVenditaMonete = QtWidgets.QLabel(self.frameVendita)
        self.labelVenditaMonete.setGeometry(QtCore.QRect(30, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelVenditaMonete.setFont(font)
        self.labelVenditaMonete.setStyleSheet('color:black;\nbackground-color: transparent;\nborder:0px;\nfont:18px;')
        self.labelVenditaMonete.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.labelVenditaMonete.setObjectName('labelVenditaMonete')
        self.labelVenditaBanconote = QtWidgets.QLabel(self.frameVendita)
        self.labelVenditaBanconote.setGeometry(QtCore.QRect(220, 20, 111, 401))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelVenditaBanconote.setFont(font)
        self.labelVenditaBanconote.setStyleSheet('color:black;\nbackground-color: transparent;\nborder:0px;\nfont:18px;')
        self.labelVenditaBanconote.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.labelVenditaBanconote.setObjectName('labelVenditaBanconote')
        self.pushButtonPlus1 = QtWidgets.QPushButton(self.frameVendita)
        self.pushButtonPlus1.setGeometry(QtCore.QRect(110, 60, 31, 31))
        self.pushButtonPlus1.setStyleSheet('background-color:yellow;\nfont:30px;\nborder-radius:0px;')
        self.pushButtonPlus1.setObjectName('pushButtonPlus1')
        self.pushButtonPlus2 = QtWidgets.QPushButton(self.frameVendita)
        self.pushButtonPlus2.setGeometry(QtCore.QRect(110, 100, 31, 31))
        self.pushButtonPlus2.setStyleSheet('background-color:yellow;\nfont:30px;\nborder-radius:0px;')
        self.pushButtonPlus2.setObjectName('pushButtonPlus2')
        self.pushButtonPlus5 = QtWidgets.QPushButton(self.frameVendita)
        self.pushButtonPlus5.setGeometry(QtCore.QRect(110, 140, 31, 31))
        self.pushButtonPlus5.setStyleSheet('background-color:yellow;\nfont:30px;\nborder-radius:0px;')
        self.pushButtonPlus5.setObjectName('pushButtonPlus5')
        self.pushButtonPlus10 = QtWidgets.QPushButton(self.frameVendita)
        self.pushButtonPlus10.setGeometry(QtCore.QRect(110, 180, 31, 31))
        self.pushButtonPlus10.setStyleSheet('background-color:yellow;\nfont:30px;\nborder-radius:0px;')
        self.pushButtonPlus10.setObjectName('pushButtonPlus10')
        self.pushButtonPlus20 = QtWidgets.QPushButton(self.frameVendita)
        self.pushButtonPlus20.setGeometry(QtCore.QRect(110, 220, 31, 31))
        self.pushButtonPlus20.setStyleSheet('background-color:yellow;\nfont:30px;\nborder-radius:0px;')
        self.pushButtonPlus20.setObjectName('pushButtonPlus20')
        self.pushButtonPlus50 = QtWidgets.QPushButton(self.frameVendita)
        self.pushButtonPlus50.setGeometry(QtCore.QRect(110, 260, 31, 31))
        self.pushButtonPlus50.setStyleSheet('background-color:yellow;\nfont:30px;\nborder-radius:0px;')
        self.pushButtonPlus50.setObjectName('pushButtonPlus50')
        self.pushButtonPlus100 = QtWidgets.QPushButton(self.frameVendita)
        self.pushButtonPlus100.setGeometry(QtCore.QRect(110, 300, 31, 31))
        self.pushButtonPlus100.setStyleSheet('background-color:yellow;\nfont:30px;\nborder-radius:0px;')
        self.pushButtonPlus100.setObjectName('pushButtonPlus100')
        self.pushButtonPlus200 = QtWidgets.QPushButton(self.frameVendita)
        self.pushButtonPlus200.setGeometry(QtCore.QRect(110, 340, 31, 31))
        self.pushButtonPlus200.setStyleSheet('background-color:yellow;\nfont:30px;\nborder-radius:0px;')
        self.pushButtonPlus200.setObjectName('pushButtonPlus200')
        self.pushButtonPlus500 = QtWidgets.QPushButton(self.frameVendita)
        self.pushButtonPlus500.setGeometry(QtCore.QRect(310, 60, 31, 31))
        self.pushButtonPlus500.setStyleSheet('background-color:yellow;\nfont:30px;\nborder-radius:0px;')
        self.pushButtonPlus500.setObjectName('pushButtonPlus500')
        self.pushButtonPlus1000 = QtWidgets.QPushButton(self.frameVendita)
        self.pushButtonPlus1000.setGeometry(QtCore.QRect(310, 100, 31, 31))
        self.pushButtonPlus1000.setStyleSheet('background-color:yellow;\nfont:30px;\nborder-radius:0px;')
        self.pushButtonPlus1000.setObjectName('pushButtonPlus1000')
        self.pushButtonPlus2000 = QtWidgets.QPushButton(self.frameVendita)
        self.pushButtonPlus2000.setGeometry(QtCore.QRect(310, 140, 31, 31))
        self.pushButtonPlus2000.setStyleSheet('background-color:yellow;\nfont:30px;\nborder-radius:0px;')
        self.pushButtonPlus2000.setObjectName('pushButtonPlus2000')
        self.pushButtonPlus5000 = QtWidgets.QPushButton(self.frameVendita)
        self.pushButtonPlus5000.setGeometry(QtCore.QRect(310, 180, 31, 31))
        self.pushButtonPlus5000.setStyleSheet('background-color:yellow;\nfont:30px;\nborder-radius:0px;')
        self.pushButtonPlus5000.setObjectName('pushButtonPlus5000')
        self.pushButtonPlus10000 = QtWidgets.QPushButton(self.frameVendita)
        self.pushButtonPlus10000.setGeometry(QtCore.QRect(310, 220, 31, 31))
        self.pushButtonPlus10000.setStyleSheet('background-color:yellow;\nfont:30px;\nborder-radius:0px;')
        self.pushButtonPlus10000.setObjectName('pushButtonPlus10000')
        self.pushButtonPlusAccParziale = QtWidgets.QPushButton(self.frameVendita)
        self.pushButtonPlusAccParziale.setGeometry(QtCore.QRect(220, 300, 141, 41))
        self.pushButtonPlusAccParziale.setStyleSheet('background-color:red;\nfont:16px;\nborder-radius:0px;')
        self.pushButtonPlusAccParziale.setObjectName('pushButtonPlusAccParziale')
        self.pushButtonPlusRestituisci = QtWidgets.QPushButton(self.frameVendita)
        self.pushButtonPlusRestituisci.setGeometry(QtCore.QRect(220, 360, 141, 41))
        self.pushButtonPlusRestituisci.setStyleSheet('background-color:red;\nfont:16px;\nborder-radius:0px;')
        self.pushButtonPlusRestituisci.setObjectName('pushButtonPlusRestituisci')
        self.labelRefill = QtWidgets.QLabel(self.frameVendita)
        self.labelRefill.setGeometry(QtCore.QRect(430, 20, 201, 401))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelRefill.setFont(font)
        self.labelRefill.setStyleSheet('color:black;\nbackground-color: transparent;\nborder:0px;\nfont:18px;')
        self.labelRefill.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.labelRefill.setObjectName('labelRefill')
        self.labelVenditaMonete1 = QtWidgets.QLabel(self.frameVendita)
        self.labelVenditaMonete1.setGeometry(QtCore.QRect(30, 65, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelVenditaMonete1.setFont(font)
        self.labelVenditaMonete1.setStyleSheet('color:black;\nbackground-color: transparent;\nborder:0px;\nfont:18px;')
        self.labelVenditaMonete1.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.labelVenditaMonete1.setObjectName('labelVenditaMonete1')
        self.labelVenditaMonete2 = QtWidgets.QLabel(self.frameVendita)
        self.labelVenditaMonete2.setGeometry(QtCore.QRect(30, 105, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelVenditaMonete2.setFont(font)
        self.labelVenditaMonete2.setStyleSheet('color:black;\nbackground-color: transparent;\nborder:0px;\nfont:18px;')
        self.labelVenditaMonete2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.labelVenditaMonete2.setObjectName('labelVenditaMonete2')
        self.labelVenditaMonete5 = QtWidgets.QLabel(self.frameVendita)
        self.labelVenditaMonete5.setGeometry(QtCore.QRect(30, 145, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelVenditaMonete5.setFont(font)
        self.labelVenditaMonete5.setStyleSheet('color:black;\nbackground-color: transparent;\nborder:0px;\nfont:18px;')
        self.labelVenditaMonete5.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.labelVenditaMonete5.setObjectName('labelVenditaMonete5')
        self.labelVenditaMonete10 = QtWidgets.QLabel(self.frameVendita)
        self.labelVenditaMonete10.setGeometry(QtCore.QRect(30, 185, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelVenditaMonete10.setFont(font)
        self.labelVenditaMonete10.setStyleSheet('color:black;\nbackground-color: transparent;\nborder:0px;\nfont:18px;')
        self.labelVenditaMonete10.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.labelVenditaMonete10.setObjectName('labelVenditaMonete10')
        self.labelVenditaMonete20 = QtWidgets.QLabel(self.frameVendita)
        self.labelVenditaMonete20.setGeometry(QtCore.QRect(30, 225, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelVenditaMonete20.setFont(font)
        self.labelVenditaMonete20.setStyleSheet('color:black;\nbackground-color: transparent;\nborder:0px;\nfont:18px;')
        self.labelVenditaMonete20.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.labelVenditaMonete20.setObjectName('labelVenditaMonete20')
        self.labelVenditaMonete50 = QtWidgets.QLabel(self.frameVendita)
        self.labelVenditaMonete50.setGeometry(QtCore.QRect(30, 265, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelVenditaMonete50.setFont(font)
        self.labelVenditaMonete50.setStyleSheet('color:black;\nbackground-color: transparent;\nborder:0px;\nfont:18px;')
        self.labelVenditaMonete50.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.labelVenditaMonete50.setObjectName('labelVenditaMonete50')
        self.labelVenditaMonete100 = QtWidgets.QLabel(self.frameVendita)
        self.labelVenditaMonete100.setGeometry(QtCore.QRect(30, 305, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelVenditaMonete100.setFont(font)
        self.labelVenditaMonete100.setStyleSheet('color:black;\nbackground-color: transparent;\nborder:0px;\nfont:18px;')
        self.labelVenditaMonete100.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.labelVenditaMonete100.setObjectName('labelVenditaMonete100')
        self.labelVenditaMonete200 = QtWidgets.QLabel(self.frameVendita)
        self.labelVenditaMonete200.setGeometry(QtCore.QRect(30, 345, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelVenditaMonete200.setFont(font)
        self.labelVenditaMonete200.setStyleSheet('color:black;\nbackground-color: transparent;\nborder:0px;\nfont:18px;')
        self.labelVenditaMonete200.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.labelVenditaMonete200.setObjectName('labelVenditaMonete200')
        self.labelVenditaBanconote5 = QtWidgets.QLabel(self.frameVendita)
        self.labelVenditaBanconote5.setGeometry(QtCore.QRect(220, 65, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelVenditaBanconote5.setFont(font)
        self.labelVenditaBanconote5.setStyleSheet('color:black;\nbackground-color: transparent;\nborder:0px;\nfont:18px;')
        self.labelVenditaBanconote5.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.labelVenditaBanconote5.setObjectName('labelVenditaBanconote5')
        self.labelVenditaBanconote10 = QtWidgets.QLabel(self.frameVendita)
        self.labelVenditaBanconote10.setGeometry(QtCore.QRect(220, 105, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelVenditaBanconote10.setFont(font)
        self.labelVenditaBanconote10.setStyleSheet('color:black;\nbackground-color: transparent;\nborder:0px;\nfont:18px;')
        self.labelVenditaBanconote10.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.labelVenditaBanconote10.setObjectName('labelVenditaBanconote10')
        self.labelVenditaBanconote20 = QtWidgets.QLabel(self.frameVendita)
        self.labelVenditaBanconote20.setGeometry(QtCore.QRect(220, 145, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelVenditaBanconote20.setFont(font)
        self.labelVenditaBanconote20.setStyleSheet('color:black;\nbackground-color: transparent;\nborder:0px;\nfont:18px;')
        self.labelVenditaBanconote20.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.labelVenditaBanconote20.setObjectName('labelVenditaBanconote20')
        self.labelVenditaBanconote50 = QtWidgets.QLabel(self.frameVendita)
        self.labelVenditaBanconote50.setGeometry(QtCore.QRect(220, 185, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelVenditaBanconote50.setFont(font)
        self.labelVenditaBanconote50.setStyleSheet('color:black;\nbackground-color: transparent;\nborder:0px;\nfont:18px;')
        self.labelVenditaBanconote50.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.labelVenditaBanconote50.setObjectName('labelVenditaBanconote50')
        self.labelVenditaBanconote100 = QtWidgets.QLabel(self.frameVendita)
        self.labelVenditaBanconote100.setGeometry(QtCore.QRect(220, 225, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelVenditaBanconote100.setFont(font)
        self.labelVenditaBanconote100.setStyleSheet('color:black;\nbackground-color: transparent;\nborder:0px;\nfont:18px;')
        self.labelVenditaBanconote100.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.labelVenditaBanconote100.setObjectName('labelVenditaBanconote100')
        self.labelWarning = QtWidgets.QLabel(self.centralwidget)
        self.labelWarning.setGeometry(QtCore.QRect(595, 435, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelWarning.setFont(font)
        self.labelWarning.setStyleSheet('background:transparent;\ncolor:red;')
        self.labelWarning.setText('')
        self.labelWarning.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelWarning.setObjectName('labelWarning')
        self.labelMess = QtWidgets.QLabel(self.centralwidget)
        self.labelMess.setGeometry(QtCore.QRect(250, 435, 491, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelMess.setFont(font)
        self.labelMess.setStyleSheet('background:transparent;\ncolor:white;\nfont:14px;')
        self.labelMess.setText('')
        self.labelMess.setObjectName('labelMess')
        self.frameImpostazioni.raise_()
        self.frameMain.raise_()
        self.labelVersione.raise_()
        self.labelVNE.raise_()
        self.frameVendita.raise_()
        self.labelWarning.raise_()
        self.labelMess.raise_()
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate('MainWindow', 'VNE'))
        self.labelVersione.setText(_translate('MainWindow', 'AC simulator\nversion 1.0'))
        self.pushButtonImpostazioniAdmin.setText(_translate('MainWindow', 'Impostazioni'))
        self.pushButtonRiepilogo.setText(_translate('MainWindow', 'Riepilogo'))
        self.labelWaiting.setText(_translate('MainWindow', 'Cassa attiva'))
        self.pushButtonEsciImpostazioni.setText(_translate('MainWindow', 'Back'))
        self.labelLingua.setText(_translate('MainWindow', 'Seleziona lingua:'))
        self.labelValuta.setText(_translate('MainWindow', 'Seleziona valuta:'))
        self.labelJCM.setText(_translate('MainWindow', 'Tagli Riciclatore'))
        self.comboBoxJCM.setItemText(0, _translate('MainWindow', '2'))
        self.comboBoxJCM.setItemText(1, _translate('MainWindow', '4'))
        self.pushButtonClean.setText(_translate('MainWindow', 'Cancella pagamenti\ne file di log'))
        self.labelVenditaInCorso.setText(_translate('MainWindow', 'Stato pagamento'))
        self.labelVenditaRichiesto.setText(_translate('MainWindow', 'Richiesto'))
        self.labelVenditaInserito.setText(_translate('MainWindow', 'Inserito'))
        self.labelVenditaResto.setText(_translate('MainWindow', 'Resto'))
        self.lineEditRichiesto.setText(_translate('MainWindow', '1000.00'))
        self.lineEditInserito.setText(_translate('MainWindow', '10'))
        self.lineEditResto.setText(_translate('MainWindow', '10'))
        self.labelVenditaMonete.setText(_translate('MainWindow', 'Monete'))
        self.labelVenditaBanconote.setText(_translate('MainWindow', 'Banconote'))
        self.pushButtonPlus1.setText(_translate('MainWindow', '+'))
        self.pushButtonPlus2.setText(_translate('MainWindow', '+'))
        self.pushButtonPlus5.setText(_translate('MainWindow', '+'))
        self.pushButtonPlus10.setText(_translate('MainWindow', '+'))
        self.pushButtonPlus20.setText(_translate('MainWindow', '+'))
        self.pushButtonPlus50.setText(_translate('MainWindow', '+'))
        self.pushButtonPlus100.setText(_translate('MainWindow', '+'))
        self.pushButtonPlus200.setText(_translate('MainWindow', '+'))
        self.pushButtonPlus500.setText(_translate('MainWindow', '+'))
        self.pushButtonPlus1000.setText(_translate('MainWindow', '+'))
        self.pushButtonPlus2000.setText(_translate('MainWindow', '+'))
        self.pushButtonPlus5000.setText(_translate('MainWindow', '+'))
        self.pushButtonPlus10000.setText(_translate('MainWindow', '+'))
        self.pushButtonPlusAccParziale.setText(_translate('MainWindow', 'Accetta parziale'))
        self.pushButtonPlusRestituisci.setText(_translate('MainWindow', 'Restituisci'))
        self.labelRefill.setText(_translate('MainWindow', 'Refill in corso\n\n\n'))
        self.labelVenditaMonete1.setText(_translate('MainWindow', '1 cent'))
        self.labelVenditaMonete2.setText(_translate('MainWindow', '2 cent'))
        self.labelVenditaMonete5.setText(_translate('MainWindow', '5 cent'))
        self.labelVenditaMonete10.setText(_translate('MainWindow', '10 cent'))
        self.labelVenditaMonete20.setText(_translate('MainWindow', '20 cent'))
        self.labelVenditaMonete50.setText(_translate('MainWindow', '50 cent'))
        self.labelVenditaMonete100.setText(_translate('MainWindow', '1 euro'))
        self.labelVenditaMonete200.setText(_translate('MainWindow', '2 euro'))
        self.labelVenditaBanconote5.setText(_translate('MainWindow', '5 euro'))
        self.labelVenditaBanconote10.setText(_translate('MainWindow', '10 euro'))
        self.labelVenditaBanconote20.setText(_translate('MainWindow', '20 euro'))
        self.labelVenditaBanconote50.setText(_translate('MainWindow', '50 euro'))
        self.labelVenditaBanconote100.setText(_translate('MainWindow', '100 euro'))


if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
